//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoExam
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class demo_examEntities : DbContext
    {
        public static demo_examEntities _context;
        public demo_examEntities()
            : base("name=demo_examEntities")
        {
        }

        public static demo_examEntities GetContext()
        {
            if (_context == null)
                _context = new demo_examEntities();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Заказы> Заказы { get; set; }
        public virtual DbSet<Категории_товаров> Категории_товаров { get; set; }
        public virtual DbSet<Корзина> Корзина { get; set; }
        public virtual DbSet<Наименования_товаров> Наименования_товаров { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Поставщики> Поставщики { get; set; }
        public virtual DbSet<Производители> Производители { get; set; }
        public virtual DbSet<Пункты_выдачи> Пункты_выдачи { get; set; }
        public virtual DbSet<Роли_пользователей> Роли_пользователей { get; set; }
        public virtual DbSet<Статусы_заказов> Статусы_заказов { get; set; }
        public virtual DbSet<Товары> Товары { get; set; }
    }
}
