//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoExam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказы()
        {
            this.Корзина = new HashSet<Корзина>();
        }
    
        public int id_заказа { get; set; }
        public Nullable<double> Номер_заказа { get; set; }
        public Nullable<System.DateTime> Дата_заказа { get; set; }
        public Nullable<System.DateTime> Дата_доставки { get; set; }
        public Nullable<int> id_пвз { get; set; }
        public Nullable<int> id_пользователя { get; set; }
        public Nullable<double> Код_для_получения { get; set; }
        public Nullable<int> id_статуса_заказа { get; set; }
    
        public virtual Пользователи Пользователи { get; set; }
        public virtual Пункты_выдачи Пункты_выдачи { get; set; }
        public virtual Статусы_заказов Статусы_заказов { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Корзина> Корзина { get; set; }
    }
}
