//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoExam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Корзина
    {
        public int id_корзины { get; set; }
        public Nullable<int> id_заказа { get; set; }
        public Nullable<int> id_товара { get; set; }
        public Nullable<double> Количество { get; set; }
    
        public virtual Заказы Заказы { get; set; }
        public virtual Товары Товары { get; set; }
    }
}
