//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demoExam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Товары
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товары()
        {
            this.Корзина = new HashSet<Корзина>();
        }
    
        public int id_товара { get; set; }
        public string Артикул { get; set; }
        public Nullable<int> id_наименования_товара { get; set; }
        public string Единица_измерения { get; set; }
        public Nullable<double> Цена { get; set; }
        public Nullable<int> id_поставщика { get; set; }
        public Nullable<int> id_производителя { get; set; }
        public Nullable<int> id_категории_товара { get; set; }
        public Nullable<double> Действующая_скидка { get; set; }
        public Nullable<double> Кол_во_на_складе { get; set; }
        public string Описание_товара { get; set; }
        public string Фото { get; set; }
    
        public virtual Категории_товаров Категории_товаров { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Корзина> Корзина { get; set; }
        public virtual Наименования_товаров Наименования_товаров { get; set; }
        public virtual Поставщики Поставщики { get; set; }
        public virtual Производители Производители { get; set; }

        // Цена тоавра с учетом скидки
        public double ЦенаСоСкидкой
        {
            get
            {
                return (Цена ?? 0) - (Цена ?? 0) * (Действующая_скидка ?? 0) / 100;
            }
        }

        // Проверкак отсутствия товара на складе
        public bool НетНаСкладе
        {
            get
            {
                return (Кол_во_на_складе ?? 0) == 0;
            }
        }

        // Проверка наличия скидки более 15%
        public bool БольшаяСкидка
        {
            get
            {
                return (Действующая_скидка ?? 0) > 15;
            }
        }
         
        // Фото и заглушка
        public string ПутьФото
        {
            get
            {
                if (string.IsNullOrEmpty(Фото))
                    return "/Resources/picture.png";

                return "/Resources/" + Фото;
            }
        }
    }
}
